### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by francicco** [glennhickey/progressiveCactus#115]
Hi,

I'm trying to install progressiveCactus following your instructions:

```
git clone git://github.com/glennhickey/progressiveCactus.git
cd progressiveCactus
git pull
git submodule update --init
make
```

but `make` returns me this error

```
cd submodules && make all
make[1]: Entering directory `/home/fc464/software/progressiveCactus/submodules'
rm -f /home/fc464/software/progressiveCactus/submodules/../environment
python2.7 /home/fc464/software/progressiveCactus/submodules/virtualenv/virtualenv.py /home/fc464/software/progressiveCactus/python
New python executable in /home/fc464/software/progressiveCactus/python/bin/python2.7
Not overwriting existing python script /home/fc464/software/progressiveCactus/python/bin/python (you must use /home/fc464/software/progressiveCactus/python/bin/python2.7)
Installing setuptools, pip, wheel...
  Complete output from command /home/fc464/software...python/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/fc464/miniconda2/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/fc464/miniconda2/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /home/fc464/software/progressiveCactus/python/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyCodec_LookupTextEncoding
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/fc464/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 2331, in <module>
    main()
  File "/home/fc464/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/home/fc464/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 943, in create_environment
    download=download,
  File "/home/fc464/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/fc464/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/fc464/software...python/bin/python2.7 - setuptools pip wheel failed with error code 1
make[1]: *** [virtPyRule] Error 1
make[1]: Leaving directory `/home/fc464/software/progressiveCactus/submodules'
make: *** [all] Error 2
```

**Comment by diekhans** [comment]
I suspect this is a problem with your python install.

A couple of quick google indicate that this could be caused by multiple
version of python on PYTHONPATH:
  https://lists.freebsd.org/pipermail/freebsd-questions/2016-October/273993.html

**Comment by francicco** [comment]
Could be the conda version of python interfering. Do I have to use the python in progressiveCactus or my own?
F
