### ISSUE TITLE
progressive_schedule fails

### ISSUE THREAD

**Issue by vpymerel** [glennhickey/progressiveCactus#132]
Hello !

I am trying to use cactus (docker) to align ~10 insects genomes and I got the following error for job 'progressive_schedule' :

---[2022-10-30T02:45:26+0200] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker progressive_schedule file:/scratch/vmerel/WGA/Cactus/LG6/jobStore kind-progressive_schedule/instance-_9ny79_l.
[2022-10-30T02:45:26+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_schedule' kind-progressive_schedule/instance-_9ny79_l v1
Exit reason: None
[2022-10-30T02:45:26+0200] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'progressive_schedule' kind-progressive_schedule/instance-_9ny79_l v2
[2022-10-30T02:45:26+0200] [MainThread] [W] [toil.leader] Log from job "kind-progressive_schedule/instance-_9ny79_l" follows:
=========>
	[2022-10-30T02:45:26+0200] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2022-10-30T02:45:26+0200] [MainThread] [I] [toil] Running Toil version 5.7.1-b5cae9634820d76cb6c13b2a6312895122017d54 on host dna068.
	[2022-10-30T02:45:26+0200] [MainThread] [I] [toil.worker] Working on job 'progressive_schedule' kind-progressive_schedule/instance-_9ny79_l v1
	[2022-10-30T02:45:26+0200] [MainThread] [I] [toil.worker] Loaded body Job('progressive_schedule' kind-progressive_schedule/instance-_9ny79_l v1) from description 'progressive_schedule' kind-progressive_schedule/instance-_9ny79_l v1
	Traceback (most recent call last):
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 407, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2406, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2324, in _run
	    return self.run(fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2547, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 147, in progressive_schedule
	    raise RuntimeError("Unable to schedule job dependencies.  Please file a bug report on github")
	RuntimeError: Unable to schedule job dependencies.  Please file a bug report on github
	[2022-10-30T02:45:26+0200] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host dna068
<=========

Can you help me please ?

Thank you !
V

**Comment by glennhickey** [comment]
Can you please share your input tree?

**Comment by vpymerel** [comment]
Yes sure,

Here it is:
(BGIGI:0.216097,(((TGE_A:0.00174569,TGE_H20:0.0018409):0.00325768,TPA:0.00711254):0.0110921,(((TCM:0.00370156,TSI:0.00335399):0.00562986,(TDI:0.00349392,TPS:0.0069705):0.00518438):0.0073258,(TCE:0.0131574,TMS:0.00461954):0.00878047):0.00799635)TIMEMA:0.186162);

--root TIMEMA

Thank you !
