### ISSUE TITLE
Build troubles

### ISSUE THREAD

**Issue by iminkin** [glennhickey/progressiveCactus#4]
I'm using Open Suse 12.3 installed just from scratch (Live CD). Content of stderr is at:

http://pastebin.com/download.php?i=47nBVaG5

On which distro it is possible to install progressiveCactus without problems?

**Comment by fbemm** [comment]
Trying to setup pCactus I get: 

cd submodules && make all
make[1]: Entering directory `/ebio/abt6/fbemm/software/progressiveCactus/submodules'
rm -f /ebio/abt6/fbemm/software/progressiveCactus/submodules/../environment
python /ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv.py /ebio/abt6/fbemm/software/progressiveCactus/python
New python executable in /ebio/abt6/fbemm/software/progressiveCactus/python/bin/python
Installing setuptools............
  Complete output from command /ebio/abt6/fbemm/sof...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" /ebio/abt6/fbemm/sof...ols-0.6c11-py2.7.egg:
  Traceback (most recent call last):
  File "<string>", line 279, in <module>
  File "<string>", line 239, in main
  File "/ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 12, in <module>
  File "/ebio/abt6/fbemm/software/anaconda-2.1.0/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/ebio/abt6/fbemm/software/anaconda-2.1.0/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /ebio/abt6/fbemm/software/progressiveCactus/python/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyLong_AsInt
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "/ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 2471, in <module>
    main()
  File "/ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 942, in main
    never_download=options.never_download)
  File "/ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1052, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "/ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 599, in install_setuptools
    search_dirs=search_dirs, never_download=never_download)
  File "/ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 571, in _install_req
    cwd=cwd)
  File "/ebio/abt6/fbemm/software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1020, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /ebio/abt6/fbemm/sof...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])

" /ebio/abt6/fbemm/sof...ols-0.6c11-py2.7.egg failed with error code 1
make[1]: *** [virtPyRule] Error 1
make[1]: Leaving directory `/ebio/abt6/fbemm/software/progressiveCactus/submodules'
make: *** [all] Error 2

Any Ideas? make starts failing during setting up setup tools. I am using anaconda as python distribution. Thx!

**Comment by fbemm** [comment]
Trying to setup pCactus I get: 

cd submodules && make all
make[1]: Entering directory `software/progressiveCactus/submodules'
rm -f software/progressiveCactus/submodules/../environment
python software/progressiveCactus/submodules/virtualenv/virtualenv.py software/progressiveCactus/python
New python executable in software/progressiveCactus/python/bin/python
Installing setuptools............
  Complete output from command sof...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" sof...ols-0.6c11-py2.7.egg:
  Traceback (most recent call last):
  File "<string>", line 279, in <module>
  File "<string>", line 239, in main
  File "software/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 12, in <module>
  File "software/anaconda-2.1.0/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "software/anaconda-2.1.0/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: software/progressiveCactus/python/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyLong_AsInt
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 2471, in <module>
    main()
  File "software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 942, in main
    never_download=options.never_download)
  File "software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1052, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 599, in install_setuptools
    search_dirs=search_dirs, never_download=never_download)
  File "software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 571, in _install_req
    cwd=cwd)
  File "software/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1020, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command sof...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])

" sof...ols-0.6c11-py2.7.egg failed with error code 1
make[1]: *** [virtPyRule] Error 1
make[1]: Leaving directory `software/progressiveCactus/submodules'
make: *** [all] Error 2

Any Ideas? make starts failing during setting up setup tools. I am using anaconda as python distribution. Thx!
