### ISSUE TITLE
git submodule update --init

### ISSUE THREAD

**Issue by rlbc** [glennhickey/progressiveCactus#43]
I'm having a problem installing progressiveCactus. When it's time to pass the "git submodule update --init" command, an error occur (error 403). The error is copied in this message.

Any help would be appreciated...
Thanks!

```
Submodule 'submodules/biopython' (https://github.com/biopython/biopython.git) registered for path 'submodules/biopython'
Submodule 'submodules/cactus' (git://github.com/benedictpaten/cactus.git) registered for path 'submodules/cactus'
Submodule 'submodules/cactus2hal' (git://github.com/glennhickey/cactus2hal.git) registered for path 'submodules/cactus2hal'
Submodule 'submodules/cactusTestData' (git://github.com/UCSCReconGroup/cactusTestData.git) registered for path 'submodules/cactusTestData'
Submodule 'submodules/clapack' (git://github.com/UCSCReconGroup/clapack) registered for path 'submodules/clapack'
Submodule 'submodules/drmaa-python' (git://github.com/UCSCReconGroup/drmaa-python) registered for path 'submodules/drmaa-python'
Submodule 'submodules/hal' (git://github.com/glennhickey/hal.git) registered for path 'submodules/hal'
Submodule 'submodules/hdf5' (git://github.com/UCSCReconGroup/hdf5.git) registered for path 'submodules/hdf5'
Submodule 'submodules/jobTree' (git://github.com/benedictpaten/jobTree.git) registered for path 'submodules/jobTree'
Submodule 'submodules/kyotocabinet' (git://github.com/UCSCReconGroup/kyotocabinet.git) registered for path 'submodules/kyotocabinet'
Submodule 'submodules/kyototycoon' (git://github.com/UCSCReconGroup/kyototycoon.git) registered for path 'submodules/kyototycoon'
Submodule 'submodules/matchingAndOrdering' (git://github.com/benedictpaten/matchingAndOrdering.git) registered for path 'submodules/matchingAndOrdering'
Submodule 'submodules/networkx' (git://github.com/networkx/networkx.git) registered for path 'submodules/networkx'
Submodule 'submodules/pbs-drmaa' (git://github.com/UCSCReconGroup/pbs-drmaa) registered for path 'submodules/pbs-drmaa'
Submodule 'submodules/phast' (git://github.com/UCSCReconGroup/phast) registered for path 'submodules/phast'
Submodule 'submodules/pinchesAndCacti' (git://github.com/benedictpaten/pinchesAndCacti.git) registered for path 'submodules/pinchesAndCacti'
Submodule 'submodules/psutil' (git://github.com/tamentis/psutil.git) registered for path 'submodules/psutil'
Submodule 'submodules/sonLib' (git://github.com/benedictpaten/sonLib.git) registered for path 'submodules/sonLib'
Submodule 'submodules/tokyocabinet' (git://github.com/UCSCReconGroup/tokyocabinet.git) registered for path 'submodules/tokyocabinet'
Submodule 'submodules/virtualenv' (git://github.com/pypa/virtualenv.git) registered for path 'submodules/virtualenv'
Submodule 'submodules/zlib' (git://github.com/madler/zlib) registered for path 'submodules/zlib'
Initialized empty Git repository in /cactus/progressiveCactus/submodules/biopython/.git/
fatal: https://github.com/biopython/biopython.git/info/refs download error - The requested URL returned error: 403
Clone of 'https://github.com/biopython/biopython.git' into submodule path 'submodules/biopython' failed
```

**Comment by joelarmstrong** [comment]
Hey Rafael,

I think you may be using a quite old version of Git which doesn't support the newer HTTP transport (Github stopped supporting the old backwards-compatible HTTP transport a while back).

I've updated the biopython submodule url to use the git:// protocol, though. Hopefully if you do a `git pull`, followed by `git submodule sync` and `git submodule update --init`, you should be good to go.

**Comment by rlbc** [comment]
Hi Joel,

It worked perfectly! Thank you very much.

I have downloaded all submodules and compiled progressiveCactus. But now, when I try to run, I get the following message from python:

```
Traceback (most recent call last):
  File "./../src/progressiveCactus.py", line 37, in <module>
    from sonLib.bioio import logger
  File ".../cactus/progressiveCactus/submodules/sonLib/bioio.py", line 17, in <module>
    from argparse import ArgumentParser
ImportError: No module named argparse
```

I'm not sure why It's not finding argparse..

**Comment by glennhickey** [comment]
It could be that your Python is too old.  Cactus requires Python 2.7.  You
can see which version you have by typing python --version.

**Comment by rlbc** [comment]
Thanks!

I didn't realize, but I don't have version 2.7... will update now.

Thank you for all the help.

**Comment by ramoserica** [comment]
I had the same issue with python version and I cannot remove or update to 2.7 version because some other algorithms are using older libraries of pyhton. Because of this, I have installed to path an alternative python, but the progressiveCactus script keep running with the oldest version. How can I set the correct python link to the script?

**Comment by renhamm** [comment]
I am having the same initial problem with the "git submodule update --init" command, but this work around doesn't fix it. I have the most recent git update the the "git submodule sync" command runs just fine, but I am still getting the same error.

**Comment by glennhickey** [comment]
https://github.com/ComparativeGenomicsToolkit/cactus/releases

**Comment by renhamm** [comment]
This link takes me to Cactus and not ProgressiveCactus. Was that intentional?

**Comment by glennhickey** [comment]
https://github.com/glennhickey/progressiveCactus#important-progressive-cactus-has-moved-here
