### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by anubhabkhan** [glennhickey/progressiveCactus#70]
Hi,

I just started using progressive Cactus. I get the following error:
Traceback (most recent call last):
  File "path/progressiveCactus/bin/./../src/progressiveCactus.py", line 37, in <module>
    from sonLib.bioio import logger
  File "path/progressiveCactus/submodules/sonLib/bioio.py", line 719
    valid_chars = {x for x in string.ascii_letters + "-"}
                       ^
SyntaxError: invalid syntax

My input was:
path/progressiveCactus/bin/./runProgressiveCactus.sh --maxThreads 100 path/reference.fasta path/wrdir path/wrdir

I am unable to understand what went wrong. can someone help?

thanks

**Comment by glennhickey** [comment]
Are you using Python 2.7?

**Comment by anubhabkhan** [comment]
my python 2.7 was not getting called by default. now I changed the following line in the .sh file:
{envFile} && eval python2.7 ${binDir}/../src/progressiveCactus.py "$options"

is it okay?

**Comment by anubhabkhan** [comment]
Hi,
Do you think the problem is because of the scheduler I use? The cluster I use is a torque scheduler.

thanks

**Comment by jq2252** [comment]
I have the same problem.
I can run it in my mac with python 2.7.
But When I run it in redhat 6.9, with python 2.7 or python 3.6, there is exception as following:
Traceback (most recent call last):
  File "bin/../src/progressiveCactus.py", line 37, in <module>
    from sonLib.bioio import logger
  File "/progressiveCactus/submodules/sonLib/bioio.py", line 719
    valid_chars = {x for x in string.ascii_letters + "-"}
with 
python --version
Python 2.7.13 :: Anaconda 4.4.0 (64-bit)
or 
python --version
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
