### ISSUE TITLE
Makefile:19: recipe for target 'virtPyRule' failed

### ISSUE THREAD

**Issue by kingcohn1** [glennhickey/progressiveCactus#74]
I am attempting to build this software in order to do a reference based assembly using ~500Mbases of a ~200K contain draft assembly against a ~640Mbase ~20K scaffolded reference using Ragout-2.0-linux-x86_64 and progressiveCactus in order to create a Hal file. However, I am getting the following make error:

```
" /home/molecularecolo...ols-0.6c11-py2.7.egg failed with error code 1
Makefile:19: recipe for target 'virtPyRule' failed
make[1]: *** [virtPyRule] Error 1
make[1]: Leaving directory '/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
``` 

Please let me know what I can do to properly build your program. Thank you.

**Comment by kingcohn1** [comment]
here's the complete error 
```
/progressiveCactus$ make
cd submodules && make all
make[1]: Entering directory '/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules'
rm -f /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/../environment
python /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/python
New python executable in /home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/python/bin/python
Installing setuptools...................................
  Complete output from command /home/molecularecolo...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" /home/molecularecolo...ols-0.6c11-py2.7.egg:
  Traceback (most recent call last):
  File "<string>", line 279, in <module>
  File "<string>", line 240, in main
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1712, in main
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 125, in finalize_options
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/easy_install.py", line 1121, in _expand
  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv_support/setuptools-0.6c11-py2.7.egg/setuptools/command/install.py", line 32, in finalize_options
  File "/usr/lib/python2.7/distutils/command/install.py", line 321, in finalize_options
    (prefix, exec_prefix) = get_config_vars('prefix', 'exec_prefix')
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/python/lib/python2.7/distutils/__init__.py", line 92, in sysconfig_get_config_vars
    real_vars = old_get_config_vars(*args)
  File "/usr/lib/python2.7/distutils/sysconfig.py", line 513, in get_config_vars
    func()
  File "/usr/lib/python2.7/distutils/sysconfig.py", line 457, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 2471, in <module>
    main()
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 942, in main
    never_download=options.never_download)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1052, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 599, in install_setuptools
    search_dirs=search_dirs, never_download=never_download)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 571, in _install_req
    cwd=cwd)
  File "/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules/virtualenv/virtualenv.py", line 1020, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/molecularecolo...us/python/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" /home/molecularecolo...ols-0.6c11-py2.7.egg failed with error code 1
Makefile:19: recipe for target 'virtPyRule' failed
make[1]: *** [virtPyRule] Error 1
make[1]: Leaving directory '/home/molecularecology/Desktop/zcpb/assemblers/ragout-2.0-linux-x86_64/progressiveCactus/submodules'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by joelarmstrong** [comment]
You may have solved this already, but I think this is a bug with the Ubuntu (maybe Debian as well?) python2.7 package. If you have administrator access, you can try running the command they suggest here:

https://stackoverflow.com/questions/15608236/eclipse-and-google-app-engine-importerror-no-module-named-sysconfigdata-nd-u

If you don't have administrator access, you could try installing Python2.7 in a local directory--this is what I have to do on my cluster system, since we run an old version of CentOS which has a similar issue.
