### ISSUE TITLE
environment must add biopython to PYTHONPATH but does not

### ISSUE THREAD

**Issue by malcook** [glennhickey/progressiveCactus#83]
i've successfully installed and run the blanchette00 test as

`bin/runProgressiveCactus.sh examples/blanchette00.txt ./work ./work/b00.hal
`

However, trying to create a hub:

`submodules/hal/bin/hal2assemblyHub.py --gcContent --maxThreads=4 --defaultMemory=10000000000 ./work/b00.hal  ./work/b00.hub
`

fails producing:
`Traceback (most recent call last):
  File "submodules/hal/bin/hal2assemblyHub.py", line 28, in <module>
    from hal.assemblyHub.prepareHubFiles import *
  File "/n/core/Bioinformatics/analysis/Sanchez/wew/cbio.wew.100/progressiveCactus/submodules/hal/assemblyHub/prepareHubFiles.py", line 16, in <module>
    from Bio import Phylo
ImportError: No module named Bio
`

examining the environment file, I see this line:

`export PYTHONPATH=/path/to/installation/progressiveCactus/submodules:$PYTHONPATH
`
Bio::Phylo is found after I additionally add

`export PYTHONPATH=/path/to/installation/progressiveCactus/submodules/biopython:$PYTHONPATH
`

Provision for this should probably have been done as part of  eab16d26f59de58aae0e42d2c1c5a9065da5b238

By the way, to protect against whitespace issues, you should probably write the above with quotes, as:

`export PYTHONPATH="/path/to/installation/progressiveCactus/submodules/biopython":"${PYTHONPATH}"
`

**Comment by malcook** [comment]
Hi - by my sights this appears to have been resolved.
