### ISSUE TITLE
HAL Export error.  converter does not support adding more than one non-leaf:Anc1

### ISSUE THREAD

**Issue by malcook** [glennhickey/progressiveCactus#88]
Hi.  Testing a fresh build of cactus emits a new error when running example:

```
bin/runProgressiveCactus.sh examples/blanchette00.txt ./test/blanchette00 ./test/blanchette00/b00.hal
```

Following is relevant tail from cactus.log

```
2017-10-06 17:46:19.267497: Beginning HAL Export

hal exception caught: Fatal Tree error.  converter does not support adding more than one non-leaf:Anc1

real	0m0.046s
user	0m0.027s
sys	0m0.011s
rm -f ./test/blanchette00/b00.hal
time halAppendCactusSubtree '/home/mec/local/src/progressiveCactus/test/blanchette00/progressiveAlignment/Anc0/Anc0_hal.c2h' '/home/mec/local/src/progressiveCactus/test/blanchette00/progressiveAlignment/Anc0/Anc0_hal.fa' '(Anc1:0.02326,Anc2:0.04)Anc0;' './test/blanchette00/b00.hal'
time halAppendCactusSubtree '/home/mec/local/src/progressiveCactus/test/blanchette00/progressiveAlignment/Anc1/Anc1_hal.c2h' '/home/mec/local/src/progressiveCactus/test/blanchette00/progressiveAlignment/Anc1/Anc1_hal.fa' '((Anc3:0.11,Anc4:0.260342)Anc1:0.02326,Anc2:0.04)Anc0;' './test/blanchette00/b00.hal' --outgroups Anc2
Traceback (most recent call last):
  File "/home/mec/local/src/progressiveCactus/submodules/cactus2hal/bin/cactus2hal.py", line 125, in <module>
    main();
  File "/home/mec/local/src/progressiveCactus/submodules/cactus2hal/bin/cactus2hal.py", line 116, in main
    system(cmdline)
  File "/home/mec/local/src/progressiveCactus/submodules/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: time halAppendCactusSubtree '/home/mec/local/src/progressiveCactus/test/blanchette00/progressiveAlignment/Anc1/Anc1_hal.c2h' '/home/mec/local/src/progressiveCactus/test/blanchette00/progressiveAlignment/Anc1/Anc1_hal.fa' '((Anc3:0.11,Anc4:0.260342)Anc1:0.02326,Anc2:0.04)Anc0;' './test/blanchette00/b00.hal' --outgroups Anc2 exited with non-zero status 1

```

**Comment by joelarmstrong** [comment]
Oops, sorry. I pushed a new version of the cactus submodule, which worked for my progressiveCactus install, but I didn't remember I was using newer versions of a lot of the submodules. I've pushed an update to the cactus2hal submodule which should fix that.

Running:
```
(in progressiveCactus dir)
git pull
git submodule update --init
make ucsc
```
should hopefully fix things. Thanks for the bug report!

**Comment by malcook** [comment]
Fix Confirmed!   Running:

    runProgressiveCactus.sh --overwrite examples/blanchette00.txt ./test/blanchette00 ./test/blanchette00/msa.hal  --defaultCpu=20  --maxThreads=20  --logInfo --logFile ./test/blanchette00_LOG.txt

....no longer emits error.

Alas, the job seems never to return, leaving 21 idle python processes, and a runProgressiveCactus.sh  idle process, etc

But, the job otherwise seems to have completed, with last line in cactus.log being:

    2017-10-07 16:43:03.890871: Finished HAL Export 

which file passes `halValidate`

Should I report this as a new issue?
