### ISSUE TITLE
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by abmudd** [glennhickey/progressiveCactus#93]
I received the following error when installing the hdf5 submodule:

```
if [ ! -d "hdf5" ]; then wget http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz && tar zxf hdf5-1.10.1.tar.gz && mv hdf5-1.10.1 hdf5; fi
--2017-10-28 17:50:14--  http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz
Resolving www.hdfgroup.org... 23.185.0.1, 2620:12a:8001::1, 2620:12a:8000::1
Connecting to www.hdfgroup.org|23.185.0.1|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz [following]
--2017-10-28 17:50:16--  https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz
Connecting to www.hdfgroup.org|23.185.0.1|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
make[1]: *** [hdf5Rule] Error 4
make[1]: Leaving directory progressiveCactus/submodules
make: *** [all] Error 2
```

To fix this issue, I manually downloaded the hdf5 tar.gz file, but I wanted to alert you to this potential problem. Thank you.

**Comment by prvnmora** [comment]
unable to access 'https://user:password@github.com/edk2/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Does any one have idea how to fix this ?

**Comment by davidcorehab** [comment]
I have the same problem,
no idea to fix it ?

**Comment by mixxael** [comment]
Work for me on Windows: update git to latest version (2.16) and remove old version ( 1.9)

**Comment by ravisingla** [comment]
I have upgraded with latest version (2.16) but still face the same problem. Can you please help me to sort out the issue?
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by jonathan1055** [comment]
I have this problem too. It is caused by https://githubengineering.com/crypto-removal-notice/

I've updated to latest git (2.3.5 because I am using an old mac), updated to OpenSSL 1.1.0g (Nov 2017) and also set the git config to use tlsv1.2 by doing git config --global --add http.sslVersion tlsv1.2. Still I get the same error about 'tlsv1 alert protocol version'

**Comment by ravisingla** [comment]
Its working for me now with the help of git config to use tlsv1.2 by doing git config --global --add http.sslVersion tlsv1.2

Thanks Jonathan

**Comment by jonathan1055** [comment]
That's great, thanks for the reply ravisingla. Now I know that the config bit does work (for you). So something is still forcing my git to use tlsv1

**Comment by hukai916** [comment]
I had a similar problem (OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version) when downing from GitHub using wget. Tried all above, none worked out.
Then I upgrade wget from 1.5 to 1.9, then wget is back to live. I guess the old wget is not compatible with some of the newest dependencies.

**Comment by Remiol** [comment]
Same problem here:fatal: unable to access 'https://github.com/kien/ctrlp.vim.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by tejkiranchambal** [comment]
I had also older version of git and now I am using git version 2.16.3.windows.1. Its working for me now with the help of git config to use tlsv1.2 by doing git config --global --add http.sslVersion tlsv1.2
**Remember go to git shell and run the above command.**

**Comment by il-bianco** [comment]
I'm using git version 2.3.5 on mac osx 10.8.5 and I'm having the same issue:
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
I'm pretty sure I'm using tlsv1.2 running:
openssl s_client -connect www.usatoday.com:443
So why running "git clone something" I get the "tlsv1 alert protocol version" error?

**Comment by delasource** [comment]
I face the same issues on a clients webhosting. I confirmed that openssl was outdated:
```
#> openssl version
OpenSSL 0.9.8o 01 Jun 2010
```
I guess that has to do with this. I'm asking the host provider to update his system.

**Comment by psyborg55** [comment]
> Then I upgrade wget from 1.5 to 1.9

wtf you sayin, 1.9 is from 2003.

**Comment by EZZAHED** [comment]
This git command resolved my problem
`git config --global --add http.sslVersion tlsv1.2
`
Hope so for you

**Comment by 85599** [comment]
> i am also facing problem similar to this
> error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
> does any one have Idea on this ?

Please try in GitHub desktop.

**Comment by 20kilograma** [comment]
fatal: unable to access 'https://github.com/gorilla/mux/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
package github.com/gorilla/mux: exit status 128

**Please Help**

**Comment by seanoconnor3000** [comment]
re installing wget using brew worked for me:
`brew install wget`
`brew link --overwrite wget`

**Comment by arthare** [comment]
Updating wget on windows (and updating my git version to get a new mingw openssl) solved it for me on windows.  I used `chocolatey install wget` to get wget updated.

**Comment by appoloniagithub** [comment]
Error: 140610921851776:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:658:
npm ERR! 
npm ERR!     at CleartextStream._puller (tls.js:649:24)
npm ERR!     at CleartextStream.CryptoStream._pull (tls.js:583:19)
npm ERR!     at SecurePair.cycle (tls.js:873:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:267:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.EventEmitter.emit (events.js:96:17)
npm ERR!     at TCP.onread (net.js:396:14)

I am getting this error, while installing socket.io, please help.
git version 2.34.1, OpenSSL 3.0.2

**Comment by sec13b** [comment]
example :   
wget --no-check-certificate -O test.zip https://github.com/test.zip
